[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ah_shell"
version = "1.0.0"
description = "Execute shell commands and dir tree"
requires-python = ">=3.7"
dependencies = ["gitignore_parser"]

